#!/usr/bin/env bash

set -Eeuxo pipefail

oldver_file=old.json
newver_file=new.json
source_file=sources.toml

nvchecker --failures --tries 5 --file "$source_file"

# Exit early if no changes
if cmp --quiet "$oldver_file" "$newver_file"; then
    echo "::notice::No updates were found."
    exit 0
fi

outdated="$(nvcmp --file "$source_file")"

git config --global user.name "github-actions[bot]"
git config --global user.email "github-actions[bot]@users.noreply.github.com"

while read -r name oldver delta newver; do
    release_url="$(jq -r ".data[\"$name\"].url // empty" "$newver_file")"

    branch_name="update-${name}-${newver}"

    # Skip if branch already exists
    if git ls-remote --heads origin "$branch_name" | grep -q "$branch_name"; then
        echo "::warning::Branch $branch_name already exists. Skipping."
        continue
    fi

    git switch "$GITHUB_REF_NAME"
    git switch --create "$branch_name"

    # Update the specific entry in oldver file
    nvtake --file "$source_file" "$name"

    git add "$oldver_file"
    commit_message="nvchecker: $name $oldver $delta $newver"
    git commit --message "$commit_message"
    git push --set-upstream origin "$branch_name"

    # Merge request body
    pr_body="$name: \`$oldver\` $delta \`$newver\`"
    if [ -n "$release_url" ]; then
        pr_body+=$'\n\n**Release URL:** '
        pr_body+="$release_url"
    fi
    pr_body+=$'\n\n---\n*This pull request was automatically generated by '
    pr_body+="[this GitHub Actions run](https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID).*"

    # Create merge request
    if ! curl --fail --silent --show-error --location --retry 5 \
        --header "Authorization: Bearer $GITHUB_TOKEN" \
        --header "Accept: application/vnd.github+json" \
        --data "$(jq --null-input \
            --arg title "$commit_message" \
            --arg body "$pr_body" \
            --arg source_branch "$branch_name" \
            --arg target_branch "$GITHUB_REF_NAME" \
            '{
                title: $title,
                body: $body,
                base: $target_branch,
                head: $source_branch,
                maintainer_can_modify: false,
            }')" \
        "https://api.github.com/repos/$GITHUB_REPOSITORY/pulls"
    then
        echo "::error::Failed to create merge request, deleting branch."
        git push origin --delete "$branch_name"
        exit 1
    fi
done <<< "$outdated"
