[__config__]
oldver = "old.json"
newver = "new.json"

[atuin]
source = "github"
github = "atuinsh/atuin"
use_latest_release = true
prefix = "v"

[hiddify]
source = "github"
github = "hiddify/hiddify-app"
use_latest_release = true
prefix = "v"
